#!/bin/sh
sp="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
echo -ne '\uf7c9 / free: '

DIR="${BLOCK_INSTANCE:-$HOME}"
ALERT_LOW="${1:-10}" # color will turn red under this value (default: 10%)

df -h -P -l "$DIR" | awk -v alert_low=$ALERT_LOW '
/\/.*/ {
	# full text
	print $4

	# short text
	#print $4

	use=$5

	# no need to continue parsing
	exit 0
}

END {
	gsub(/%$/,"",use)
	if (100 - use < alert_low) {
		# color
		print "-"
#		print "#8afeb7"
#		print "#aaaaaa"
}
  else {
		print "-"
#    print "#aaaaaa"
#    print "#cc6666"
	}
}
'


