#!/bin/sh
sp="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
nix-shell -p python3 python3Packages.pip python3Packages.setuptools python3Packages.virtualenv python3Packages.psutil --run "$sp/mem"



