#!/bin/bash
if ! hash iwconfig; then exit 1; fi
INTERFACE="${BLOCK_INSTANCE:-wlp3s0}"
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
ap="$(iwconfig 2>/dev/null | grep ESSID | cut -d":" -f 2- | sed 's|"||g' | sed -E 's/ +$//')"
echo "$QUALITY% [$ap]" # full text
echo "$QUALITY% [$ap]" # short text
if [[ $QUALITY -ge 80 ]]; then
    sleep 0
elif [[ $QUALITY -lt 80 ]]; then
    sleep 0
elif [[ $QUALITY -lt 60 ]]; then
    echo "#bb9999"
elif [[ $QUALITY -lt 40 ]]; then
    echo "#cc8888"
fi
